#web服务器启动端口
server:
  port: 8080
  
spring:
  redis:
    #IP地址
    host: 192.168.49.91
    #端口
    port: 6379 
    #密码
    password: 5vwJ4AghYNH&W4RWejfieo69C2ZPp%r@
    ssl: false
  #rabbitmq配置  
  rabbitmq:
    #IP地址
    host: 192.168.49.91
    #端口
    port: 5672
    #用户名
    username: admin
    #密码
    password: admin    
   
mqtt:
  urls:
  - tcp://192.168.49.91:1883
  username: qjzh2020
  password: qjzh2020
  qos: 1
  time-to-wait: 10000


      
      
    