#web服务器启动端口
server:
  port: 8080
   
spring:
  application:
    name: iots-hub-mqtt

mqtt:
  urls:
  - tcp://192.168.49.91:1883
  username: qjzh2020
  password: qjzh2020
  qos: 1


      
      
    